name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Updated to 18 (16 is End-of-Life)

      - name: Install Dependencies
        # We cd into the folder to install
        run: cd elias-website-app && npm install

      - name: Build Application
        # We cd into the folder to build
        run: cd elias-website-app && CI=false npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./elias-website-app/build 
          cname: www.eliasmeana.com
          keep_files: false # Changed to false to ensure old files are cleaned up
